In [1]:
import numpy as np

In [2]:
a= [1,2,3,4,5]

In [3]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.arange(10,20,2.4)
arr2

array([10. , 12.4, 14.8, 17.2, 19.6])

In [6]:
arr2 = np.arange(10,20,2.4)
arr2

array([10. , 12.4, 14.8, 17.2, 19.6])

In [7]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr3.size

9

In [9]:
arr3.ndim

2

In [10]:
arr3.dtype

dtype('int32')

In [11]:
arr3.max()

9

In [12]:
arr3.min()

1

In [13]:
arr3.sum()

45

In [14]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr3.prod()

362880

In [16]:
arr3.mean()

5.0

In [17]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.arange(1,9, dtype ='complex').reshape(2,2,2)

array([[[1.+0.j, 2.+0.j],
        [3.+0.j, 4.+0.j]],

       [[5.+0.j, 6.+0.j],
        [7.+0.j, 8.+0.j]]])

In [19]:
mat1=np.arange(1,21).reshape(4,5)
mat1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [20]:
mat1 = np.arange(1,21).reshape(4,5)
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
mat1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [22]:
mat1*3

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60]])

In [23]:
#wap to check which element in mat1 are divisible by 2

In [24]:
b_arr = mat1%2 ==0
b_arr]

SyntaxError: unmatched ']' (Temp/ipykernel_2300/2095659595.py, line 2)

In [ ]:
mat1[b_arr]

NameError: name 'mat1' is not defined

In [ ]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
mat1[mat1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

indexing


In [ ]:
mat1[1,3]

9

In [ ]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
mat1[2,4

15

slicing

In [ ]:
mat1[1:3,3]

array([ 9, 14])

In [ ]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
mat1[1,1:4]

array([7, 8, 9])

In [ ]:
mat1[0:2,1:5]



array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [ ]:
np.random.randint(1,20,(10,10))

array([[ 6,  8, 10,  2,  7,  8, 13,  9, 12, 10],
       [14,  8,  6,  3, 13, 10, 11, 15, 18, 10],
       [17, 18,  5, 19,  9,  1,  2,  2, 10, 17],
       [ 3, 15, 19,  8,  8,  7, 12, 12, 12, 14],
       [ 8, 17, 16,  7,  8, 19,  2, 11,  7, 18],
       [18,  3,  8, 11, 13, 10,  7, 19, 12, 12],
       [ 9,  5, 13,  1,  5, 17, 14,  7, 10, 16],
       [ 1, 11, 15,  7, 17, 13, 14, 11,  7, 14],
       [ 8, 13,  5, 14,  6,  4,  3,  8, 12, 16],
       [18, 13, 13,  2,  5, 11,  5, 13,  9, 15]])

In [ ]:
np.random.random((8,8))

array([[0.95178859, 0.21935508, 0.58649408, 0.53199323, 0.85589188,
        0.22261292, 0.44127379, 0.59019413],
       [0.12688741, 0.92660733, 0.14949984, 0.84567382, 0.57467383,
        0.39181108, 0.71084168, 0.15183504],
       [0.56426243, 0.11316213, 0.05524734, 0.12802576, 0.88072448,
        0.66104058, 0.38873658, 0.61646061],
       [0.59909345, 0.61292753, 0.75439168, 0.17363171, 0.81122606,
        0.96606357, 0.46455268, 0.59184371],
       [0.51493305, 0.51094474, 0.42506225, 0.2268064 , 0.3020654 ,
        0.71076087, 0.02869341, 0.57974354],
       [0.28480784, 0.68449635, 0.04321378, 0.37036109, 0.46652425,
        0.92966498, 0.21280846, 0.0596079 ],
       [0.63700118, 0.58827106, 0.73677762, 0.0230357 , 0.68113915,
        0.52854418, 0.19254154, 0.76686544],
       [0.07354396, 0.72432659, 0.0468583 , 0.20100135, 0.72374089,
        0.86738448, 0.12056405, 0.23622537]])

In [ ]:
mat2 = np.arange(1,7).reshape(2,3)
mat2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:

mat3 = np.arange(1,5).reshape(2,2)
mat3

array([[1, 2],
       [3, 4]])

In [ ]:
mat4 = np.arange(1,5).reshape(2,2)
mat4

array([[1, 2],
       [3, 4]])

In [ ]:
np.vstack((mat3,mat4))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [ ]:
#horizental
np.hsplit(mat3,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [ ]:
mat3.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
#sum along the diagonals
mat3.trace()

NameError: name 'mat3' is not defined

In [ ]:
f = open('data/testoutput.text')
f.write('hello world!')
f.close()

FileNotFoundError: [Errno 2] No such file or directory: 'data/testoutput.text'

In [ ]:
quotelist =quotelist.split('')
print(quotelist)

NameError: name 'quotelist' is not defined

In [ ]:
text = "Research has shown that it is often still possible to understand text even if all vowels are removed"
for vowel in ("a","i","e","o","u"):
    x = text.replace(vowel,"l")
print(text)

Research has shown that it is often still possible to understand text even if all vowels are removed


In [ ]:
fruitlist = ['banana' 'pear' 'apple']
delimiter = ","
fruitstring = delimiter.join(fruitlist)
print(fruitstring)

bananapearapple


In [ ]:
numberoftwoletterwords = 0
for word in quotelist:
    if len(word) == 2:
        numberoftwoletterwords += 1
print(numberoftwoletterwords == 5)

NameError: name 'quotelist' is not defined

In [ ]:
words = ["BlA", "plop", "blA", "Bla", "PLoP", "bLa", "pLop", "BLA"]
count = 0
for word in words:
    if word.lower() == "bla":
        count += 1
print(count)

5


In [ ]:
s = "   strip me!     "
print(s.strip())

NameError: name 'akanksha' is not defined

In [ ]:
teachers = "Folgert Karsdorp and Maarten van Gompel"
print(teachers.lower())
print(teachers.upper

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_12316/944999469.py, line 3)

In [ ]:
fruitset = {'banana', 'apple', 'pear'}
fruitset.add('banana') # will have no effect, banana already exists
fruitset.add('orange')
print(len(fruitset))

4


In [ ]:
fruittuple = ('banana','apple','pear')
print(fruittuple[0])

banana


In [ ]:
numbers = [1, 2, 3, 4, 5 ]
doublenumbers = [number*2 for number in numbers]
print(doublenumbers)

[2, 4, 6, 8, 10]


In [ ]:
numbers = [1, 2, 3, 4, 5]
numbers = [ x + 2 _ x __ numbers]

SyntaxError: invalid syntax (Temp/ipykernel_12316/3030947088.py, line 2)

In [ ]:
text = "You can not compare apples and pears"
text = text.replace("pears", "apples")
text = text.replace("not","can")
print(text)

You can can compare apples and apples
